### PR TITLE
fix: fixed magic link issues

### PR DESCRIPTION
**Pull request by JazzarKarim**
Issue #: /https://github.com/bcgov/entity/issues/24363

I fixed the magic link format in this PR: https://github.com/bcgov/sbc-auth/pull/3166

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-registry-dev--pr-33-ct3xdzhx.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-registry-dev--pr-33-ct3xdzhx.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-registry-dev--pr-33-ct3xdzhx.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-registry-dev--pr-33-ct3xdzhx.web.app

**Comment by JazzarKarim** [comment]
not needed anymore

**Pull request closed without merging**
