### PR TITLE
BRD - Feat: Dynamic table columns

### PR DESCRIPTION
**Pull request by deetz99**
issue: bcGov/entity#22871

- change table columns based on screen width
- allow users to select what columns are shown with the dropdown menu

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-registry-dev--pr-15-phndw7hn.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-registry-dev--pr-15-phndw7hn.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-registry-dev--pr-15-phndw7hn.web.app

**Review by thorwolpert — APPROVED** [review]

**Pull request merged**
