### PR TITLE
fix: fixed UXA issues in response to Jacqueline's comment

### PR DESCRIPTION
**Pull request by JazzarKarim**
Issue #: https://github.com/bcgov/entity/issues/24364

Fixed issues in response to Jacqueline's comment: https://github.com/bcgov/entity/issues/24364#issuecomment-2505056084

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-registry-dev--pr-35-bmfb9qei.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-registry-dev--pr-35-bmfb9qei.web.app

**Review by severinbeauvais — APPROVED** [review]
LGTM

**Review by ArwenQin — APPROVED** [review]
Looks good!

**Pull request merged**
